default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: v8yuricoelho
  password: pizza
  host: localhost
  port: 5432

development:
  <<: *default
  database: creating_webhooks

test:
  <<: *default
  database: creating_webhooks_test
